name: Phoenix Test Automation CI Workflow
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule: # Set CRON for midnight IST [Convert from UTC to IST]
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env: 
        description: "Environment"
        type: choice
        options: [qa, uat, dev]
        default: qa
        required: true
      suiteXMLFile: 
        description: "TestNG XML File Name"
        type: choice
        options: [testng.xml, regression.xml, sanity.xml, testng-datadriven.xml]
        default: testng.xml
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:  
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute Test Automation Framework
      if: always()
      run: mvn clean test -DsuiteXmlFile="${{ github.event.inputs.suiteXMLFile }}" -Denv="${{ github.event.inputs.env }}"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: SureFire Repports
        path: target/surefire-reports/
        retention-days: 10 # it will store for 10 days, after that it will deleted.
